# netlify.toml

[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Proxy Netlify : /api/* → Railway
[[redirects]]
  from = "/api/*"
  to = "https://kazadi-securepay-api-production.up.railway.app/api/:splat"
  status = 200
  force = true

# (Optionnel) SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
