[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Transaction → Netlify Function
[[redirects]]
  from = "/api/transaction"
  to = "/.netlify/functions/transaction"
  status = 200
  force = true

# Proxy Netlify : /kazadi/* → Railway (même préfixe qu'en dev)
[[redirects]]
  from = "/kazadi/*"
  to = "https://kazadi-securepay-api-production.up.railway.app/:splat"
  status = 200
  force = true

# (Optionnel) SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
